language: node_js
node_js:
  - "node"

# only build pushes to master
# prs are build separately
# https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built
branches:
  only:
  - master

after_success: |
  # see https://github.com/xd009642/tarpaulin/issues/150 for tarpaulin nightly dependency
  if [ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]; then
    npm coverage
  fi