service: test-svc

provider:
  name: aws
  runtime: python3.7

package:
  individually: true
  excludeDevDependencies: false

functions:
  # not an http func
  hello:
    handler: hello.handler
  # python http func
  world:
    handler: world.handler
    events:
      - http:
          path: /
          method: get
  # note http func
  js:
    handler: node.handler
    runtime: nodejs8.10
    events:
      - http:
          path: /foo/:bar
          method: get

plugins:
- serverless-localhost