service: demo

provider:
  name: aws
  runtime: python3.7
  memorySize: 128
  environment:
    FOO: bar

package:
  individually: true

functions:
  # not an http func
  hello:
    handler: hello.handler
    package:
      include:
        - hello.py
  # python http func
  index:
    handler: index.handler
    environment:
      BAR: boom
    package:
      include:
        - world.py
    events:
      - http: ANY /
  # node http func with path params
  pathparams:
    handler: pathparams.handler
    runtime: nodejs8.10
    package:
      include:
        - pathparams.js
    events:
      - http:
          path: /foo/:bar
          method: POST
  # node http func with path params
  proxyplus:
    handler: proxyplus.handler
    runtime: nodejs8.10
    package:
      include:
        - proxyplus.js
    events:
      - http:
          path: /bar/{proxy+}
          method: get

plugins:
- localhost-hooks
- serverless-localhost